DROP TABLE IF EXISTS Wages;
CREATE TABLE Wages 
(
	WageID int NOT NULL ,
	Amount money NOT NULL,
	WorkerID int NOT NULL,
	CONSTRAINT PK_Wages PRIMARY KEY NONCLUSTERED (WageID),
	CONSTRAINT PK_Wages_Workers FOREIGN KEY (WorkerID)
		REFERENCES Workers (WorkerID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
);